name: 'Pyccel pytest commands generating fortran or c'

runs:
  using: "composite"
  steps:
    - name: Test with pytest
      run: |
        pytest pygyro -m serial -vs
        mpirun -n 1 python3 mpi_tester.py pygyro -m parallel --mpisub
        mpirun -n 4 --oversubscribe python3 mpi_tester.py pygyro -m parallel --mpisub
        mpirun -n 6 --oversubscribe python3 mpi_tester.py pygyro -m parallel --mpisub
      shell: bash
