name: 'Pyccel pytest commands generating fortran or c'

runs:
  using: "composite"
  steps:
    - name: Test with pytest
      run: |
        pytest pygyro -m serial
        mpirun -n 1 mpi_tester.py pygyro -m parallel --mpisub
        mpirun -n 4 --oversubscribe mpi_tester.py pygyro -m parallel --mpisub
        mpirun -n 6 --oversubscribe mpi_tester.py pygyro -m parallel --mpisub
      shell: bash
      working-directory: ./tests
